version: '3.8'

services:
  backend:
    build:
      context: ./backend  # תיקיית ה-backend שבה קובץ Dockerfile
      dockerfile: Dockerfile  # שם קובץ Dockerfile
    container_name: backend
    image: python-app-2
    environment:
      - LISTEN_PORT=5000
    expose:
      - "5000"
    depends_on:
      - es
    networks:
      - backend
      - frontend

  es:
    image: elasticsearch:7.17.28
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
