apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: results
  ports:
    - protocol: TCP
      port: 31001
      targetPort: 80
      nodePort: 31001
  type: NodePort