apiVersion: v1
kind: Secret
metadata:
  name: voting-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
   DB_USER: {{ .Values.secret.dbUser | b64enc }}
   DB_PASSWORD: {{ .Values.secret.dbPassword | b64enc }}