apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount.vote }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: {{ .Values.images.vote }}
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: voting-app-config
              key: REDIS_PORT
        ports:
        - containerPort: 80
