apiVersion: v1
kind: Service
metadata:
  name: vote-ui-access
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: vote
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  type: NodePort